include $(S)/tests/test-avcap.mk
include $(S)/tests/test-hsb-vsrc.mk
include $(S)/tests/test-deint.mk
include $(S)/tests/test-lic.mk
include $(S)/tests/bsci-demo.mk
include $(S)/tests/test-zznvenc2.mk
include $(S)/tests/test-ipx.mk
include $(S)/tests/kylin-demo.mk
include $(S)/tests/sc6g0-aenc.mk
include $(S)/tests/test-aenc.mk
include $(S)/tests/test-freetype.mk
include $(S)/tests/test-graphics.mk
include $(S)/tests/sc6f0-dante-demo.mk
include $(S)/tests/coe-demo.mk
include $(S)/tests/test-rcbuf.mk
include $(S)/tests/roce-dmabuf-test.mk
include $(S)/tests/test-demuxer.mk
