include mkfiles/novatek_arm64.mk
include mkfiles/funcs.mk

BUILD_WITH_ZZLAB?=ON
BUILD_WITH_QCAP?=ON

BUILD_WITH_NDI_ADV_SDK?=ON
BUILD_WITH_NDI6_2?=ON
BUILD_WITH_NEON?=ON
BUILD_WITH_OPENSSL?=ON
BUILD_WITH_FREETYPE?=ON
BUILD_WITH_HARFBUZZ?=ON
BUILD_WITH_ALSA?=ON
BUILD_WITH_IREADER?=ON
BUILD_WITH_JSTS?=ON
BUILD_WITH_JSTSD?=ON
BUILD_WITH_JSBASE?=ON
BUILD_WITH_JSRTSP?=ON
BUILD_WITH_NVT_HDAL?=ON
BUILD_WITH_BRNVT?=ON
BUILD_WITH_DANTE?=ON

include mkfiles/rules.mk
