include mkfiles/xlnk2_arm64.mk
include mkfiles/funcs.mk

BUILD_WITH_ZZLAB?=ON
BUILD_WITH_QCAP?=ON

BUILD_WITH_ALSA?=ON
# BUILD_WITH_X11?=ON
# BUILD_WITH_FONTCONFIG?=ON
BUILD_WITH_FREETYPE?=ON
BUILD_WITH_HARFBUZZ?=ON
BUILD_WITH_X264?=ON
BUILD_WITH_OPENSSL?=ON
# BUILD_WITH_YUAN_CAPTURE?=ON
# BUILD_WITH_GSTREAMER?=ON
BUILD_WITH_NEON?=ON
# BUILD_WITH_NDI_ADV_SDK?=ON
# BUILD_WITH_NDICODEC?=ON
# BUILD_WITH_JSBASE?=ON
# BUILD_WITH_JSTS?=ON
# BUILD_WITH_AFSRT?=ON
BUILD_WITH_ALLEGRO2?=ON
BUILD_WITH_IREADER?=ON
# BUILD_WITH_DRM?=ON
# BUILD_WITH_JSTSD?=ON
# BUILD_WITH_DANTE?=ON
BUILD_WITH_DAUSERVICE?=ON

include mkfiles/rules.mk
